import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactNode } from 'react';
import Head from 'next/head';

import "./globals.scss";

interface LayoutProps {
  children: ReactNode;
}

// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Import Google Fonts here */}
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "'Roboto', var(--font-geist-sans), sans-serif" }} // Apply both Google Fonts and local fonts
      >
        {children}
      </body>
    </html>
  );
}
